In [1]:
from mxnet import nd

ModuleNotFoundError: No module named 'mxnet'

In [2]:
!pip install -U mxnet

  Using cached https://files.pythonhosted.org/packages/a4/3e/07f6d61d8e0a5d50c6f128791a617d7b222224c52dacba04855a0b6ecfe6/mxnet-1.5.0-py2.py3-none-win_amd64.whl
  Using cached https://files.pythonhosted.org/packages/53/39/4ab213673844e0c004bed8a0781a0721a3f6bb23eb8854ee75c236428892/graphviz-0.8.4-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl
  Found existing installation: urllib3 1.24.2
    Uninstalling urllib3-1.24.2:
      Successfully uninstalled urllib3-1.24.2
  Found existing installation: idna 2.8
    Uninstalling idna-2.8:
      Successfully uni

In [3]:
from mxnet import nd

In [6]:
nd.array(((1,2,3),(5,6,7)))


[[1. 2. 3.]
 [5. 6. 7.]]
<NDArray 2x3 @cpu(0)>

In [7]:
x = nd.ones((2,3))
x


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [9]:
y = nd.random.uniform(-1,1,(2,3))
y


[[0.09762704 0.18568921 0.43037868]
 [0.6885315  0.20552671 0.71589124]]
<NDArray 2x3 @cpu(0)>

In [10]:
x = nd.full((2,3), 2.0)
x


[[2. 2. 2.]
 [2. 2. 2.]]
<NDArray 2x3 @cpu(0)>

In [19]:
(x.shape, x.size, x.dtype)

((2, 3), 6, numpy.float32)

In [20]:
x * y


[[ 0.17953277  1.3890069  -0.30538082]
 [ 0.49425483  0.58357644 -0.46247315]]
<NDArray 2x3 @cpu(0)>

In [21]:
y.exp()


[[1.0939187  2.0027144  0.85839546]
 [1.2803422  1.3388195  0.7935517 ]]
<NDArray 2x3 @cpu(0)>

In [22]:
nd.dot(x, y.T)


[[1.2631588 0.6153581]
 [1.2631588 0.6153581]]
<NDArray 2x2 @cpu(0)>

In [23]:
y[1,2]


[-0.23123658]
<NDArray 1 @cpu(0)>

In [24]:
y[:,1:3]


[[ 0.6945034  -0.15269041]
 [ 0.29178822 -0.23123658]]
<NDArray 2x2 @cpu(0)>

In [25]:
y [:,1:3] = 2
y


[[0.08976638 2.         2.        ]
 [0.24712741 2.         2.        ]]
<NDArray 2x3 @cpu(0)>

In [26]:
y[1:2,0:2] = 4 
y


[[0.08976638 2.         2.        ]
 [4.         4.         2.        ]]
<NDArray 2x3 @cpu(0)>

In [27]:
#converting between MXNet and NDArray and NumPy
a = x.asnumpy()
(type(a), a)

(numpy.ndarray, array([[2., 2., 2.],
        [2., 2., 2.]], dtype=float32))

In [28]:
nd.array(a)


[[2. 2. 2.]
 [2. 2. 2.]]
<NDArray 2x3 @cpu(0)>